### PR TITLE
Update to Octoprint v1.5.2, update plugins, get OctoDash going

### PR DESCRIPTION
**Pull request by ajlennon**

### CODE REVIEW

**Comment by Sureiya** [comment]
Personally I like traefik, the correct way to fix this would be to run mpeg streamer in its own container, and possible on a different port, as it may just be conflicting with traefik's web address. I'd submit a PR if had the time, but probably won't get to it this week.

**Comment by MatthewCroughan** [comment]
@Sureiya There's actually a lot more wrong than just this. The upstream image I'm using (`nunofgs/octoprint`) uses HAProxy, and HAProxy generally seems to be something deeply integrated with Octoprint. OctoPi and the official Octoprint Dockerfiles both use it. I saw a lot of Gateway Timeouts when using Traefik myself over time, which aren't present when bypassing by using port 5000. Really this whole repo needs to be nuked and started over to be done right ;D

**Comment by MatthewCroughan** [comment]
To clarify, I mean to say that we're actually using Traefik on top of HAProxy, which causes some weirdness.

**Comment by MatthewCroughan** [comment]
@ajlennon I can't accept this PR because it has too many things in it that would fail to later compile, such as wgetting/curling inside the Dockerfile for Octoprint. I'd rather point people to your repo than accept it here.

**Comment by MatthewCroughan** [comment]
There are bits and pieces from this PR that I can cherry pick though, but some of it is too much to merge in one go.

**Comment by ajlennon** [comment]
Yup - I'll leave it in mine then. I prefer it to work now and break later than it not working now ;)

**Comment by MatthewCroughan** [comment]
Better than having a dysfunctional repo, although anyone reviewing this PR should know that the Dockerfiles have a lot of room for optimization, both in terms of reproducibility and image size.

**Comment by ajlennon** [comment]
> Better than having a dysfunctional repo, although anyone reviewing this PR should know that the Dockerfiles have a lot of room for optimization, both in terms of reproducibility and image size.

Absolutely ! Lots for interested contributors to do. That said if Balena is working as I think it should the overall result should be smaller I think (weirdly) as I am using a standard base rather than different Linux distros...

**Pull request merged**
